/* Kayan · Ready Products — taxonomy
   Source: KAY-PRD-001 Ready Products Operating Catalogue (85 products / 12 families)
         + KAY-CLT-006 Ready Products Catalogue v2.0 (35 fixed-price products)
         + KAY-CLT-006 Edition 2.0 AR (RP-1xx, kept as edition aliases)
   15 families · 7 buyer types · 103 products. Nothing invented. */
window.KAYAN_RP = window.KAYAN_RP || {};
window.KAYAN_RP.families = [
  { k:'brand', en:'Design & Brand', ar:'الهوية والتصميم',
    posEn:'Identity and design that make a small organisation look as serious as it is.',
    posAr:'هوية وتصميم يظهران المنشأة بحجم جديتها.' },
  { k:'digital', en:'Digital & Web', ar:'المواقع والتطوير الرقمي',
    posEn:'The digital presence a business needs to be found, trusted, and chosen.',
    posAr:'حضور رقمي يوجد به النشاط، ويوثق، ويختار.' },
  { k:'marketing', en:'Marketing & Social', ar:'التسويق ووسائل التواصل',
    posEn:'A presence that shows up every day and brings customers in.',
    posAr:'حضور يومي منتظم يجلب العملاء.' },
  { k:'content', en:'Content & Copy', ar:'المحتوى والصياغة',
    posEn:'Words that work — written in Arabic first, to persuade and to sell.',
    posAr:'نصوص تكتب بالعربية أولا، وتصاغ للإقناع والبيع.' },
  { k:'translation', en:'Translation & Documents', ar:'الترجمة والوثائق',
    posEn:'Documents made ready to cross a border, and paperwork handled by people you can trust.',
    posAr:'وثائق تجهز لتقبل خارج الحدود، وإجراءات تنجز بأيد موثوقة.' },
  { k:'data', en:'Data & AI Services', ar:'البيانات وخدمات الذكاء الاصطناعي',
    posEn:'The careful data work the modern economy runs on, at a cost that competes anywhere.',
    posAr:'عمل بيانات دقيق يقوم عليه الاقتصاد الحديث، بكلفة تنافس في أي سوق.' },
  { k:'media', en:'Media & Production', ar:'الإنتاج الإعلامي',
    posEn:'Voice, video, and image — the pieces that carry a message and make it land.',
    posAr:'صوت وصورة وفيديو تحمل الرسالة وتوصلها.' },
  { k:'business', en:'Business & Strategy', ar:'الأعمال والاستراتيجية',
    posEn:'The documents and research that win support, funding, and good decisions.',
    posAr:'وثائق وبحوث تكسب الدعم والتمويل والقرار السليم.' },
  { k:'development', en:'Development Sector', ar:'القطاع التنموي',
    posEn:'What the humanitarian and development sector needs, delivered to donor standard.',
    posAr:'ما يحتاجه القطاع الإنساني والتنموي، بمعيار المانح.' },
  { k:'finance', en:'Finance, Admin & Support', ar:'المالية والإدارة والمساندة',
    posEn:'The back office an owner should not be running personally.',
    posAr:'مكتب خلفي لا يجوز أن يديره المالك بنفسه.' },
  { k:'events', en:'Events & Experiences', ar:'الفعاليات والتنظيم',
    posEn:'Events and workshops run end to end, so the day is right and you can be present in it.',
    posAr:'فعاليات وورش تدار كاملة، فيحضر صاحبها ضيفا لا منظما.' },
  { k:'career', en:'Career & Education', ar:'المسار المهني والتعليم',
    posEn:'The bridge from a degree, or a skill, to a job or a place to study.',
    posAr:'جسر من الشهادة أو المهارة إلى وظيفة أو مقعد دراسي.' },
  { k:'enterprise', en:'Enterprise & Hospitality', ar:'الحزم المؤسسية والضيافة',
    posEn:'Multi-branch brands, hotels, and business leaders — several products delivered as one suite.',
    posAr:'علامات متعددة الفروع وفنادق وقيادات: منتجات تسلم حزمة واحدة.' },
  { k:'packages', en:'Packages for New Businesses', ar:'حزم التأسيس',
    posEn:'Everything a new company needs at once, in one funded order.',
    posAr:'ما يحتاجه النشاط الجديد كله، في أمر واحد ممول.' },
  { k:'homeland', en:'The Homeland Collection', ar:'مجموعة الوطن',
    posEn:'For Yemenis abroad — a trusted hand at home to build, to help, and to remember.',
    posAr:'لليمنيين في الخارج: يد موثوقة في الوطن تبني وتساند وتحفظ.' }
];
window.KAYAN_RP.buyers = [
  { k:'IND', en:'Individuals', ar:'الأفراد',
    whoEn:'A job seeker, a student, a professional, anyone who needs a document or a personal project done.',
    whoAr:'باحث عن عمل، أو طالب، أو مهني، أو من يحتاج وثيقة أو عملا شخصيا.',
    needEn:'CVs and careers · certified translation · personal documents · portfolios',
    needAr:'سيرة ومسار مهني · ترجمة معتمدة · وثائق شخصية · ملف أعمال' },
  { k:'FND', en:'New founders', ar:'المؤسسون الجدد',
    whoEn:'Someone starting a business who needs to look serious and get online fast.',
    whoAr:'من يبدأ نشاطا ويحتاج مظهرا جديا وحضورا سريعا.',
    needEn:'Brand · a website · social presence · a business plan',
    needAr:'هوية · موقع · حضور اجتماعي · خطة عمل' },
  { k:'SME', en:'Small & medium businesses', ar:'المنشآت الصغيرة والمتوسطة',
    whoEn:'Restaurants, hotels, clinics, shops, schools — established, but needing presence, marketing, and systems.',
    whoAr:'مطاعم وفنادق وعيادات ومتاجر ومدارس قائمة، تحتاج حضورا وتسويقا وأنظمة.',
    needEn:'Digital presence · social media · menus and print · booking systems',
    needAr:'حضور رقمي · وسائل تواصل · قوائم ومطبوعات · أنظمة حجز' },
  { k:'COR', en:'Larger businesses', ar:'الشركات الكبرى',
    whoEn:'Companies needing bigger builds, brand systems, data work, and strategy.',
    whoAr:'شركات تحتاج بناء أكبر وأنظمة هوية وعمل بيانات واستراتيجية.',
    needEn:'Platforms · brand systems · market research · data services',
    needAr:'منصات · أنظمة هوية · بحوث سوق · خدمات بيانات' },
  { k:'NGO', en:'NGOs, INGOs & UN', ar:'المنظمات والأمم المتحدة',
    whoEn:'The humanitarian and development sector — a large, active buyer in Yemen.',
    whoAr:'القطاع الإنساني والتنموي: مشتر كبير ونشط في اليمن.',
    needEn:'Proposals · reports · monitoring · field data · translation · training',
    needAr:'مقترحات · تقارير · رقابة · بيانات ميدانية · ترجمة · تدريب' },
  { k:'GOV', en:'Government & local authorities', ar:'الجهات الحكومية والسلطات المحلية',
    whoEn:'Public bodies needing digital services, reports, assessments, and capacity.',
    whoAr:'جهات عامة تحتاج خدمات رقمية وتقارير وتقييمات وقدرات.',
    needEn:'Digital services · reports · needs assessments · training',
    needAr:'خدمات رقمية · تقارير · تقييم احتياجات · تدريب' },
  { k:'DIA', en:'The diaspora — Yemenis abroad', ar:'المغتربون اليمنيون',
    whoEn:'People who want to build, help, invest, or get something done at home, and cannot be there to do it.',
    whoAr:'من يريد أن يبني أو يساند أو يستثمر أو ينجز في الوطن ولا يستطيع الحضور.',
    needEn:'A trusted hand on the ground · build-home bundles · family occasions · property · remembrance',
    needAr:'يد موثوقة على الأرض · حزم البناء · مناسبات الأسرة · العقار · الأرشيف' }
];
