/* Kayan · Ready Products — the 35 fixed-price cards
   Source: KAY-CLT-006 Ready Products Catalogue v2.0 (effective 30 Jun 2026)
         + Products & Ideas Engine v1.2 (segments, pods, waves)
   `alt` records the name the same product carries in the operating register or in Edition 2.0 (AR).
   USD, fixed. Fixed scope · fixed price · fixed date · named pod. */
window.KAYAN_RP = window.KAYAN_RP || {};
window.KAYAN_RP.fixed = [
{code:'RP-001',en:'Brand Identity Pack',ar:'حزمة الهوية البصرية الكاملة',fam:'brand',usd:500,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Designer T2+ · Arabic writer · QA · Pod lead',podAr:'مصمم هوية T2+ · كاتب عربي · مراجع جودة · قائد بود',
 solvesEn:'A new venture looks improvised, so nobody trusts it with real money.',solvesAr:'النشاط الجديد يظهر مرتجلا، فلا يؤتمن على مال جدي.',
 recEn:['Primary logo + 3 alternates — AI, SVG, PNG, PDF','Brand guide: colour, type, usage rules','Stationery: card, letterhead, envelope, e-signature','Print-ready and digital files','One free revision'],
 recAr:['شعار رئيسي + ٣ بدائل — AI · SVG · PNG · PDF','دليل هوية: الألوان والخطوط وقواعد الاستخدام','قرطاسية كاملة: بطاقة، ورق رسمي، مغلف، توقيع بريد','نسخ جاهزة للطباعة وللرقمي','مراجعة مجانية واحدة'],
 whyEn:'A complete, ownable identity for less than one month of a junior salary.',whyAr:'هوية كاملة مملوكة بأقل من أجر شهر لموظف مبتدئ.',
 buyers:['FND','SME'],wave:1,alt:'Full Brand Identity (register) · RP-101 (Edition 2.0)'},
{code:'RP-016',en:'Brand Refresh & Rebrand',ar:'تحديث الهوية وإعادة بنائها',fam:'brand',usd:950,unit:'',
 daysEn:'21 days',daysAr:'٢١ يوما',podEn:'Designer T3+ · Strategist · QA',podAr:'مصمم T3+ · مخطط · مراجع جودة',
 solvesEn:'An ageing brand quietly undercuts a business that has grown past it.',solvesAr:'هوية متقادمة تضعف نشاطا تجاوزها بالنمو.',
 recEn:['Audit of the identity in use','Refreshed logo system','Expanded palette and type scale','Messaging lines, AR and EN','Applied templates: social, documents, signage','Rollout guide'],
 recAr:['تدقيق الهوية القائمة','نظام شعار محدث','لوحة ألوان وسلم خطوط موسعان','رسائل نصية بالعربية والإنجليزية','قوالب مطبقة: تواصل، وثائق، لوحات','دليل الإحلال'],
 whyEn:'One consistent brand that matches where the business actually is now.',whyAr:'هوية متماسكة تطابق موضع النشاط اليوم.',
 buyers:['SME','COR'],wave:4,alt:''},
{code:'RP-002',en:'Professional Website',ar:'موقع إلكتروني احترافي',fam:'digital',usd:1200,unit:'',
 daysEn:'21 days',daysAr:'٢١ يوما',podEn:'Developer T2+ · UI/UX · Bilingual writer · QA',podAr:'مطور T2+ · واجهة وتجربة · كاتب ثنائي اللغة · مراجع جودة',
 solvesEn:'No credible presence online, so clients and donors cannot find you or verify you.',solvesAr:'لا حضور موثوق على الشبكة، فلا يجد العميل ولا المانح ما يتحقق منه.',
 recEn:['Responsive 5–7 page bilingual site, Arabic RTL and English','Custom design, not a template','Basic search optimisation','SSL and first-year hosting','One hour of CMS training','Two free revisions'],
 recAr:['موقع متجاوب ٥–٧ صفحات، ثنائي اللغة: عربي من اليمين وإنجليزي','تصميم مخصص لا قالب جاهز','تحسين أساسي لمحركات البحث','شهادة SSL واستضافة السنة الأولى','ساعة تدريب على إدارة المحتوى','مراجعتان مجانيتان'],
 whyEn:'A bilingual, credible web presence for the price of a single overseas mock-up.',whyAr:'حضور رقمي موثوق ثنائي اللغة بسعر تصميم واحد في الخارج.',
 buyers:['SME','NGO','FND'],wave:1,alt:'RP-102 (Edition 2.0)'},
{code:'RP-008',en:'MVP Web Application',ar:'تطوير تطبيق ويب — النسخة الأولى',fam:'digital',usd:2000,unit:'',
 daysEn:'30 days',daysAr:'٣٠ يوما',podEn:'Full-stack T3+ · UI/UX · QA · PM',podAr:'مطور متكامل T3+ · واجهة وتجربة · مراجع جودة · مدير مشروع',
 solvesEn:'An idea cannot be tested, or shown to an investor, without something that runs.',solvesAr:'الفكرة لا تختبر ولا تعرض على مستثمر دون منتج يعمل.',
 recEn:['Responsive web application, 5–8 screens','Login and user management','Database and admin dashboard','Custom UI/UX','Testing and bug-fixing','Technical documentation and first deployment'],
 recAr:['تطبيق ويب متجاوب، ٥–٨ شاشات','دخول وإدارة مستخدمين','قاعدة بيانات ولوحة تحكم','واجهة وتجربة مخصصتان','اختبار ومعالجة أخطاء','وثائق تقنية ونشر أولي'],
 whyEn:'A working, demoable product at a fraction of an overseas dev-shop quote.',whyAr:'منتج عامل قابل للعرض بجزء من عرض شركة خارجية.',
 buyers:['FND','COR'],wave:4,alt:'App MVP (register) · RP-302 (Edition 2.0)'},
{code:'RP-017',en:'E-commerce Storefront',ar:'متجر إلكتروني متكامل',fam:'digital',usd:1600,unit:'',
 daysEn:'25 days',daysAr:'٢٥ يوما',podEn:'Developer T2+ · UI/UX · Writer · QA',podAr:'مطور متاجر T2+ · واجهة وتجربة · كاتب · مراجع جودة',
 solvesEn:'A seller lives on WhatsApp orders: no storefront, no record, no scale.',solvesAr:'البائع معلق بطلبات واتساب: لا متجر ولا سجل ولا نمو.',
 recEn:['Online store, up to 30 products','Local payment or cash on delivery, plus delivery options','Bilingual throughout','Photo editing for 30 products','Admin training','Opening promotion set'],
 recAr:['متجر حتى ٣٠ منتجا','دفع محلي أو عند الاستلام، مع خيارات التوصيل','ثنائي اللغة كاملا','معالجة صور ٣٠ منتجا','تدريب على الإدارة','حزمة ترويج الافتتاح'],
 whyEn:'A real store that takes orders while the owner sleeps.',whyAr:'متجر يستقبل الطلبات وصاحبه نائم.',
 buyers:['SME','FND'],wave:3,alt:'Online Store (register) · RP-103 (Edition 2.0)'},
{code:'RP-021',en:'Mobile App — iOS & Android',ar:'تطبيق هاتف — iOS و Android',fam:'digital',usd:3800,unit:'',
 daysEn:'45 days',daysAr:'٤٥ يوما',podEn:'Mobile dev T3+ · UI/UX · QA · PM',podAr:'مطور هاتف T3+ · واجهة وتجربة · مراجع جودة · مدير مشروع',
 solvesEn:'The idea needs a real app to reach customers, and overseas quotes open above $10,000.',solvesAr:'الفكرة تحتاج تطبيقا حقيقيا، وعروض الخارج تبدأ فوق عشرة آلاف دولار.',
 recEn:['Cross-platform app on iOS and Android, up to 10 screens','User accounts and push notifications','Backend API and admin panel','Submission to both stores','Bilingual','Testing and 30 days of post-launch support'],
 recAr:['تطبيق يعمل على iOS و Android، حتى ١٠ شاشات','حسابات مستخدمين وإشعارات','واجهة برمجية خلفية ولوحة إدارة','رفع إلى المتجرين','ثنائي اللغة','اختبار ومساندة ٣٠ يوما بعد الإطلاق'],
 whyEn:'A published app on both stores for a fraction of a studio quote.',whyAr:'تطبيق منشور على المتجرين بجزء من عرض استوديو.',
 buyers:['FND','COR','GOV'],wave:4,alt:''},
{code:'RP-022',en:'Custom Web Platform',ar:'منصة ويب مخصصة',fam:'digital',usd:5500,unit:'',
 daysEn:'8–12 weeks',daysAr:'٨–١٢ أسبوعا',podEn:'Full-stack T4 · UI/UX · QA · PM',podAr:'مطور متكامل T4 · واجهة وتجربة · مراجع جودة · مدير مشروع',
 solvesEn:'Off-the-shelf software forces the organisation to work the vendor’s way.',solvesAr:'البرمجيات الجاهزة تلزم المؤسسة بطريقة المورد لا بطريقتها.',
 recEn:['Bespoke platform with your own workflows','Multi-role user management','Integrations: payment, SMS, maps','Admin dashboard and reporting','Bilingual','Documentation and training','Deployment and 60 days of support'],
 recAr:['منصة مخصصة بمسارات عملك','إدارة مستخدمين متعددي الأدوار','تكاملات: دفع، رسائل، خرائط','لوحة إدارة وتقارير','ثنائي اللغة','توثيق وتدريب','نشر ومساندة ٦٠ يوما'],
 whyEn:'A platform built around how you actually work — owned, not rented.',whyAr:'منصة مبنية على طريقة عملك، مملوكة لا مستأجرة.',
 buyers:['COR','NGO','GOV'],wave:4,alt:'Custom Platform (register)'},
{code:'RP-023',en:'IT & DevOps Care',ar:'رعاية تقنية وتشغيل',fam:'digital',usd:500,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'DevOps T3+ · Support',podAr:'مهندس تشغيل T3+ · دعم',
 solvesEn:'Sites and apps break quietly, and downtime is lost revenue.',solvesAr:'المواقع تتعطل بصمت، والتوقف إيراد مفقود.',
 recEn:['Hosting and domain management','Uptime monitoring','Weekly backups','Security updates','Up to 8 fix hours a month','Monthly health report'],
 recAr:['إدارة الاستضافة والنطاق','مراقبة الإتاحة','نسخ احتياطي أسبوعي','تحديثات أمنية','حتى ٨ ساعات إصلاح شهريا','تقرير حالة شهري'],
 whyEn:'Someone is watching the site, so it never quietly breaks.',whyAr:'أحد يراقب الموقع، فلا يتعطل بصمت.',
 buyers:['SME','COR'],wave:4,alt:'Website Care Plan (register)'},
{code:'RP-024',en:'AI Automation & Chatbot',ar:'أتمتة ومساعد محادثة',fam:'digital',usd:750,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Developer T2+ · Content · QA',podAr:'مطور T2+ · محتوى · مراجع جودة',
 solvesEn:'The owner answers the same three questions all day, and loses the enquiries that arrive at night.',solvesAr:'المالك يرد على الأسئلة الثلاثة نفسها طول اليوم، وتضيع استفسارات الليل.',
 recEn:['WhatsApp or web chatbot, bilingual','FAQ and lead-capture flows','One workflow automated: orders or bookings into a sheet','Handover to a human','Setup and training'],
 recAr:['مساعد محادثة على واتساب أو الموقع، ثنائي اللغة','مسارات الأسئلة الشائعة والتقاط الطلبات','أتمتة مسار واحد: الطلبات أو الحجوزات إلى جدول','تحويل إلى موظف عند الحاجة','تجهيز وتدريب'],
 whyEn:'An assistant that does not tire, answering and capturing leads around the clock.',whyAr:'مساعد لا يتعب، يرد ويلتقط الطلبات على مدار الساعة.',
 buyers:['SME','COR'],wave:3,alt:''},
{code:'RP-003',en:'Launch Marketing Pack',ar:'حزمة تسويق الإطلاق',fam:'marketing',usd:750,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Marketer T2+ · Designer · Writer',podAr:'مسوق T2+ · مصمم · كاتب',
 solvesEn:'A launch lands in silence, and the most valuable week is spent.',solvesAr:'الإطلاق يمر بصمت، فيهدر أثمن أسبوع.',
 recEn:['10-page launch strategy','15 social posts, design and copy, AR and EN','Account setup on 3 platforms','Email template and 3 drafts','Competitor analysis'],
 recAr:['استراتيجية إطلاق في ١٠ صفحات','١٥ منشورا: تصميم ونص، بالعربية والإنجليزية','تجهيز ٣ حسابات','قالب بريد و٣ مسودات','تحليل المنافسين'],
 whyEn:'You open to a crowd, not to silence.',whyAr:'أن تفتح على جمهور، لا على صمت.',
 buyers:['FND','SME'],wave:2,alt:'Launch Campaign (register)'},
{code:'RP-004',en:'Monthly Content Pack',ar:'حزمة المحتوى الشهرية',fam:'marketing',usd:400,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Writer T2+ · Designer',podAr:'كاتب T2+ · مصمم',
 solvesEn:'The brand goes quiet a month after launch, because nobody has time to keep it visible.',solvesAr:'العلامة تسكت بعد شهر من الإطلاق، إذ لا وقت لإبقائها ظاهرة.',
 recEn:['8 social posts, design and copy','One article, 800–1,200 words','Monthly newsletter','Simple performance report','Next month’s content calendar'],
 recAr:['٨ منشورات: تصميم ونص','مقال واحد، ٨٠٠–١٢٠٠ كلمة','رسالة بريدية شهرية','تقرير أداء مبسط','تقويم محتوى الشهر القادم'],
 whyEn:'An always-on content team for a fraction of one part-time wage.',whyAr:'فريق محتوى دائم بجزء من أجر جزئي واحد.',
 buyers:['SME','FND'],wave:2,alt:''},
{code:'RP-009',en:'Social Media Management',ar:'إدارة وسائل التواصل',fam:'marketing',usd:550,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Marketer T2+ · Designer · Writer · Pod lead',podAr:'مسوق T2+ · مصمم · كاتب · قائد بود',
 solvesEn:'The owner runs the accounts personally, so posting is irregular and the tone drifts.',solvesAr:'المالك يدير الحسابات بنفسه، فيختل الانتظام ويتفاوت الخطاب.',
 recEn:['16 posts a month, design and copy, AR and EN','Two platforms managed','Guidance for replies and community','A monthly set of ad-ready creative','One boosted post set up','Monthly report'],
 recAr:['١٦ منشورا شهريا: تصميم ونص، بالعربية والإنجليزية','إدارة منصتين','إرشاد الردود والتفاعل','حزمة تصاميم شهرية جاهزة للإعلان','تجهيز منشور ممول واحد','تقرير شهري'],
 whyEn:'Show up every day without spending your day on it.',whyAr:'أن تحضر كل يوم دون أن يذهب يومك فيه.',
 buyers:['SME','FND'],wave:1,alt:'RP-104 (Edition 2.0)'},
{code:'RP-029',en:'SEO Launch & Optimisation',ar:'تحسين الظهور في محركات البحث',fam:'marketing',usd:550,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'SEO specialist T2+ · Writer',podAr:'أخصائي تحسين بحث T2+ · كاتب',
 solvesEn:'The site exists and nobody finds it.',solvesAr:'الموقع قائم ولا أحد يجده.',
 recEn:['Technical audit and fixes','Keyword research, AR and EN','On-page optimisation, up to 10 pages','Google Business and Maps listing','Analytics and Search Console','90-day action plan'],
 recAr:['تدقيق تقني ومعالجة','بحث الكلمات المفتاحية بالعربية والإنجليزية','تحسين حتى ١٠ صفحات','تسجيل النشاط على جوجل والخرائط','تحليلات وربط Search Console','خطة عمل ٩٠ يوما'],
 whyEn:'Found by the people already searching for you.',whyAr:'أن يجدك من يبحث عنك أصلا.',
 buyers:['SME','COR'],wave:2,alt:'Arabic SEO Tune-Up (register)'},
{code:'RP-030',en:'Paid Ads Management',ar:'إدارة الحملات المدفوعة',fam:'marketing',usd:500,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Ads specialist T2+ · Designer',podAr:'أخصائي إعلانات T2+ · مصمم',
 solvesEn:'Posts get boosted at random and the budget disappears without a record.',solvesAr:'ترويج عشوائي للمنشورات، فتذهب الميزانية بلا سجل.',
 recEn:['Campaign setup on Meta or Google','4 ad creatives a month','Audience targeting','Budget management','A/B testing','Monthly performance report'],
 recAr:['تجهيز الحملات على Meta أو Google','٤ تصاميم إعلانية شهريا','استهداف الجمهور','إدارة الميزانية','اختبار مقارن','تقرير أداء شهري'],
 whyEn:'Money spent on advertising that returns customers.',whyAr:'مال يصرف على إعلان يعيد عملاء.',
 buyers:['SME','COR'],wave:4,alt:'Ad Campaign Management (register) · ad spend billed to the client'},
{code:'RP-007',en:'Corporate Documents Pack',ar:'حزمة وثائق الشركة',fam:'content',usd:450,unit:'',
 daysEn:'10 days',daysAr:'١٠ أيام',podEn:'Writer T2+ · Designer · Reviewer',podAr:'كاتب T2+ · مصمم · مراجع',
 solvesEn:'Every letter and profile leaving the office looks like it came from a different company.',solvesAr:'كل خطاب وملف يخرج من المكتب يبدو صادرا عن شركة أخرى.',
 recEn:['Company profile, Arabic and English','Presentation of 15–20 slides','5 correspondence templates','3 report templates','One design language across all of it'],
 recAr:['ملف تعريفي بالعربية والإنجليزية','عرض تقديمي ١٥–٢٠ شريحة','٥ قوالب مخاطبات','٣ قوالب تقارير','لغة تصميم واحدة في الجميع'],
 whyEn:'Every document an institution hands out, in one coherent set.',whyAr:'كل ما تخرجه المؤسسة من وثائق، في طقم واحد متماسك.',
 buyers:['SME','COR','GOV'],wave:1,alt:'RP-108 (Edition 2.0)'},
{code:'RP-018',en:'Annual Report',ar:'التقرير السنوي: كتابة وتصميم',fam:'content',usd:1100,unit:'',
 daysEn:'18 days',daysAr:'١٨ يوما',podEn:'Writer T3+ · Designer · Translator',podAr:'كاتب T3+ · مصمم · مترجم',
 solvesEn:'A real year of work sits in folders, unreadable and unpresentable.',solvesAr:'سنة عمل حقيقية تقبع في ملفات، غير مقروءة ولا قابلة للعرض.',
 recEn:['Narrative writing and editing, up to 30 pages','Data visualisation','Bilingual layout','Print and digital versions','Executive summary','Two revisions'],
 recAr:['كتابة السرد وتحريره، حتى ٣٠ صفحة','تصور البيانات','إخراج ثنائي اللغة','نسخة للطباعة وأخرى رقمية','ملخص تنفيذي','مراجعتان'],
 whyEn:'A year of work turned into the document that funds the next one.',whyAr:'سنة عمل تتحول إلى الوثيقة التي تمول السنة القادمة.',
 buyers:['NGO','COR','GOV'],wave:4,alt:''},
{code:'RP-005',en:'Professional Translation',ar:'حزمة الترجمة الاحترافية',fam:'translation',usd:300,unit:'',
 daysEn:'7 days',daysAr:'٧ أيام',podEn:'Translator T2+ · Second reviewer',podAr:'مترجم T2+ · مراجع ثان',
 solvesEn:'A document has to be understood — and accepted — in another language.',solvesAr:'وثيقة يجب أن تفهم، وأن تقبل، بلغة أخرى.',
 recEn:['Up to 10,000 words, Arabic to English or English to Arabic','Review by a second translator','Final formatting, PDF and Word','A glossary kept for your account','One free revision'],
 recAr:['حتى ١٠٠٠٠ كلمة، عربي إلى إنجليزي أو العكس','مراجعة مترجم ثان','تنسيق نهائي: PDF و Word','معجم يحفظ لحسابك','مراجعة مجانية واحدة'],
 whyEn:'Two professionals on every page, for the price of one freelancer.',whyAr:'مهنيان على كل صفحة بسعر مستقل واحد.',
 buyers:['NGO','COR','IND','DIA'],wave:1,alt:'RP-301 (Edition 2.0)'},
{code:'RP-020',en:'Video & Motion Pack',ar:'حزمة الفيديو والموشن',fam:'media',usd:650,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Editor T2+ · Motion designer · Writer · QA',podAr:'محرر T2+ · مصمم موشن · كاتب · مراجع جودة',
 solvesEn:'Static posts are scrolled past, and there is no video skill in the building.',solvesAr:'المنشور الساكن يمر عليه، ولا مهارة فيديو في المنشأة.',
 recEn:['One brand or promotional video, 60–90 seconds','4 short vertical cuts for social','Subtitles in Arabic and English','Motion logo sting','Licence-safe music'],
 recAr:['فيديو ترويجي واحد، ٦٠–٩٠ ثانية','٤ مقاطع عمودية قصيرة للتواصل','سترجة بالعربية والإنجليزية','شعار متحرك','موسيقى مرخصة'],
 whyEn:'Video stops the scroll — the single highest-engagement format there is.',whyAr:'الفيديو يوقف التمرير: أعلى الصيغ تفاعلا.',
 buyers:['SME','NGO','COR'],wave:2,alt:'Social Video Pack (register) · RP-105 (Edition 2.0)'},
{code:'RP-031',en:'Voice-Over & Audio',ar:'تعليق صوتي ومعالجة سمعية',fam:'media',usd:280,unit:'',
 daysEn:'7 days',daysAr:'٧ أيام',podEn:'Voice artist T2+ · Audio editor',podAr:'مؤدي صوتي T2+ · محرر صوت',
 solvesEn:'A phone recording makes a serious message sound cheap.',solvesAr:'تسجيل الهاتف يجعل الرسالة الجدية تبدو رخيصة.',
 recEn:['Professional voice-over, AR or EN, up to 3 minutes — Yemeni dialect on request','Script polish','Clean, mastered audio','Licence-safe music bed','Two formats and one revision'],
 recAr:['تعليق صوتي مهني، بالعربية أو الإنجليزية، حتى ٣ دقائق — باللهجة اليمنية عند الطلب','صقل النص','صوت نظيف بمعالجة نهائية','خلفية موسيقية مرخصة','صيغتان ومراجعة واحدة'],
 whyEn:'A broadcast-grade voice, so the message sounds like it matters.',whyAr:'صوت بمستوى البث، فتبدو الرسالة كما تستحق.',
 buyers:['SME','COR','NGO'],wave:2,alt:'Professional Voice-Over (register) · RP-035 (Edition 2.0)'},
{code:'RP-006',en:'Market Study',ar:'دراسة سوق',fam:'business',usd:600,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Researcher T3+ · Analyst · QA',podAr:'باحث T3+ · محلل · مراجع جودة',
 solvesEn:'A decision is about to be taken on assumption instead of evidence.',solvesAr:'قرار على وشك أن يتخذ على افتراض لا على دليل.',
 recEn:['Market analysis, 20–30 pages','Analysis of 5–10 competitors','Target-audience analysis','Strategic recommendations','3-page executive summary','Presentation of findings'],
 recAr:['تحليل سوق في ٢٠–٣٠ صفحة','تحليل ٥–١٠ منافسين','تحليل الجمهور المستهدف','توصيات استراتيجية','ملخص تنفيذي في ٣ صفحات','عرض النتائج'],
 whyEn:'Know before you spend, not after.',whyAr:'أن تعرف قبل أن تصرف، لا بعده.',
 buyers:['FND','COR','GOV'],wave:3,alt:'Market Research Report (register)'},
{code:'RP-015',en:'Pitch Deck & Investor Pack',ar:'عرض تقديمي للمستثمرين',fam:'business',usd:700,unit:'',
 daysEn:'12 days',daysAr:'١٢ يوما',podEn:'Writer T3+ · Designer · Analyst',podAr:'كاتب T3+ · مصمم · محلل',
 solvesEn:'A fundable idea is being presented badly, and the room decides in ten minutes.',solvesAr:'فكرة قابلة للتمويل تعرض عرضا سيئا، والقاعة تحكم في عشر دقائق.',
 recEn:['Investor deck, 12–16 slides, AR and EN','One-page teaser','Simple 3-year financial model','Data-room checklist','Rehearsal notes'],
 recAr:['عرض استثماري ١٢–١٦ شريحة، بالعربية والإنجليزية','ملخص من صفحة واحدة','نموذج مالي مبسط لثلاث سنوات','قائمة غرفة البيانات','ملاحظات التدريب على العرض'],
 whyEn:'The ten slides that get you the next meeting.',whyAr:'الشرائح العشر التي تحصل الاجتماع التالي.',
 buyers:['FND','COR'],wave:3,alt:'Pitch Deck (register) · RP-106 (Edition 2.0)'},
{code:'RP-026',en:'Financial Model & Projections',ar:'نموذج مالي وإسقاطات',fam:'business',usd:850,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Financial modeller T3+ · Analyst · QA',podAr:'نمذجة مالية T3+ · محلل · مراجع جودة',
 solvesEn:'The numbers in the plan are guesses, and an investor will test every one.',solvesAr:'أرقام الخطة تقديرات، والمستثمر يختبرها واحدا واحدا.',
 recEn:['3-year model: revenue, costs, cash','Three scenarios','Assumptions sheet','Break-even and key ratios','Investor-ready summary','A walkthrough session'],
 recAr:['نموذج ثلاث سنوات: إيراد وكلفة ونقد','ثلاثة سيناريوهات','ورقة الافتراضات','نقطة التعادل والنسب الأساسية','ملخص جاهز للمستثمر','جلسة شرح'],
 whyEn:'Numbers built so that you and your investor both trust them.',whyAr:'أرقام تثق بها أنت والمستثمر معا.',
 buyers:['FND','COR'],wave:4,alt:'Financial Model (register)'},
{code:'RP-012',en:'NGO Report & Proposal Pack',ar:'حزمة مقترحات المانحين وتقاريرهم',fam:'development',usd:900,unit:'',
 daysEn:'12 days',daysAr:'١٢ يوما',podEn:'Writer T3+ · Designer · Translator · QA',podAr:'كاتب T3+ · مصمم · مترجم · مراجع جودة',
 solvesEn:'A donor deadline arrives and there is no capacity to write to standard.',solvesAr:'موعد المانح يحل ولا قدرة على الكتابة بالمعيار.',
 recEn:['Donor-ready report or proposal, up to 40 pages, AR and EN','Visualisation of results','Layout on the donor’s template','Executive summary','Two revisions'],
 recAr:['تقرير أو مقترح جاهز للمانح، حتى ٤٠ صفحة، بالعربية والإنجليزية','تصور النتائج','إخراج على قالب المانح','ملخص تنفيذي','مراجعتان'],
 whyEn:'Written the way funders score, and filed without a rewrite.',whyAr:'يكتب كما يقيم المانح، ويقبل دون إعادة كتابة.',
 buyers:['NGO','GOV'],wave:3,alt:'RP-201 (Edition 2.0)'},
{code:'RP-013',en:'Data Collection & Dashboard',ar:'جمع بيانات ولوحة متابعة',fam:'development',usd:1400,unit:'',
 daysEn:'21 days',daysAr:'٢١ يوما',podEn:'Data analyst T3+ · Field lead · Enumerators · QA',podAr:'محلل بيانات T3+ · قائد ميداني · باحثون · مراجع جودة',
 solvesEn:'Field returns arrive messy and late, so nothing can be built on them.',solvesAr:'العائد الميداني يصل مشوشا ومتأخرا، فلا يبنى عليه شيء.',
 recEn:['KoBo or ODK form design','One day of enumerator training','Supervised collection, sample up to 400','Cleaned dataset','Live dashboard, Power BI or Looker','Findings brief'],
 recAr:['تصميم أدوات KoBo أو ODK','يوم تدريب للباحثين','جمع مشرف، عينة حتى ٤٠٠','مجموعة بيانات منظفة','لوحة متابعة حية: Power BI أو Looker','موجز النتائج'],
 whyEn:'Reliable data from the field, and a dashboard a donor can read.',whyAr:'بيانات موثوقة من الميدان، ولوحة يقرأها المانح.',
 buyers:['NGO','GOV'],wave:3,alt:'Field Data Collection (register)'},
{code:'RP-014',en:'Monitoring & Evaluation Study',ar:'دراسة متابعة وتقييم',fam:'development',usd:2400,unit:'',
 daysEn:'30 days',daysAr:'٣٠ يوما',podEn:'M&E lead T4 · Analyst · QA',podAr:'قائد متابعة وتقييم T4 · محلل · مراجع جودة',
 solvesEn:'Impact is claimed in the report and cannot be defended in front of an evaluator.',solvesAr:'الأثر يدعى في التقرير ولا يدافع عنه أمام مقيم.',
 recEn:['Evaluation design aligned to the logframe','Tools','Mixed-method collection','Analysis','Full evaluation report, AR and EN','Validation workshop','Presentation'],
 recAr:['تصميم التقييم متوافقا مع الإطار المنطقي','الأدوات','جمع بمنهج مختلط','التحليل','تقرير تقييم كامل بالعربية والإنجليزية','ورشة تحقق','عرض'],
 whyEn:'Impact shown in a form an evaluator will accept.',whyAr:'أثر يعرض بصيغة يقبلها المقيم.',
 buyers:['NGO','GOV'],wave:4,alt:''},
{code:'RP-019',en:'Training Workshop',ar:'ورشة تدريب: تصميم وتنفيذ',fam:'development',usd:1300,unit:'',
 daysEn:'Per cohort',daysAr:'لكل دفعة',podEn:'Certified trainer T4 · Designer · Coordinator',podAr:'مدرب معتمد T4 · مصمم · منسق',
 solvesEn:'Staff need real capability, not slides read aloud.',solvesAr:'الفريق يحتاج قدرة فعلية، لا شرائح تقرأ.',
 recEn:['Curriculum design','Bilingual materials and slides','Two facilitated days, up to 20 participants','Workbooks','Certificates','Post-workshop report'],
 recAr:['تصميم المنهج','مواد وشرائح ثنائية اللغة','يومان ميسران، حتى ٢٠ مشاركا','كتب تدريب','شهادات','تقرير بعد الورشة'],
 whyEn:'Training people actually learn from, run for you.',whyAr:'تدريب يتعلم منه الناس فعلا، يدار عنك.',
 buyers:['NGO','GOV','COR'],wave:4,alt:'Training Delivery (register)'},
{code:'RP-025',en:'Bookkeeping & Accounting',ar:'إمساك دفاتر ومحاسبة',fam:'finance',usd:400,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Bookkeeper T2+ · Reviewer',podAr:'ممسك دفاتر T2+ · مراجع',
 solvesEn:'The books are months behind, and nobody can say what the month made.',solvesAr:'الدفاتر متأخرة أشهرا، ولا أحد يعرف حصيلة الشهر.',
 recEn:['Monthly books, up to 100 transactions','Bank reconciliation','Tax-ready summaries','Simple profit and cash report','Receipts organised','Year-end pack'],
 recAr:['دفاتر شهرية، حتى ١٠٠ حركة','مطابقة بنكية','ملخصات جاهزة للضريبة','قائمة أرباح ونقد مبسطة','ترتيب المستندات','حزمة إقفال السنة'],
 whyEn:'Books that are current, and one number each month you can trust.',whyAr:'دفاتر محدثة، ورقم شهري واحد يعتمد عليه.',
 buyers:['SME','FND'],wave:3,alt:''},
{code:'RP-027',en:'Virtual Assistant',ar:'مساعد إداري عن بعد',fam:'finance',usd:450,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Assistant T2+, bilingual',podAr:'مساعد T2+ ثنائي اللغة',
 solvesEn:'The founder spends the day on admin instead of on the business.',solvesAr:'المؤسس يصرف يومه في الإداريات لا في النشاط.',
 recEn:['Up to 40 remote admin hours a month','Inbox and calendar management','Data entry','Document formatting','Research','Weekly check-in'],
 recAr:['حتى ٤٠ ساعة عمل إداري شهريا','إدارة البريد والمواعيد','إدخال بيانات','تنسيق وثائق','بحث','لقاء أسبوعي'],
 whyEn:'Forty hours a month returned to you, for less than a local part-time wage.',whyAr:'أربعون ساعة تعود إليك شهريا، بأقل من أجر جزئي محلي.',
 buyers:['FND','SME','COR'],wave:4,alt:''},
{code:'RP-028',en:'Customer Service Desk',ar:'مكتب خدمة عملاء',fam:'finance',usd:650,unit:'/mo',
 daysEn:'Monthly',daysAr:'شهري متجدد',podEn:'Support agents T2+ · Lead',podAr:'موظفو دعم T2+ · مشرف',
 solvesEn:'Messages sit unanswered and after-hours orders are simply lost.',solvesAr:'الرسائل تبقى بلا رد، وطلبات ما بعد الدوام تفقد.',
 recEn:['Managed WhatsApp, social and email support in business hours','A response time you contract for','Order and enquiry handling','Bilingual','Escalation rules','Monthly satisfaction report'],
 recAr:['دعم مدار على واتساب والتواصل والبريد في ساعات العمل','مدة رد متعاقد عليها','معالجة الطلبات والاستفسارات','ثنائي اللغة','قواعد التصعيد','تقرير رضا شهري'],
 whyEn:'Every message answered and every order captured, on a monthly footing.',whyAr:'كل رسالة تجاب، وكل طلب يلتقط، بترتيب شهري.',
 buyers:['SME','COR'],wave:4,alt:''},
{code:'RP-010',en:'Restaurant Launch Kit',ar:'حزمة افتتاح مطعم',fam:'enterprise',usd:680,unit:'',
 daysEn:'18 days',daysAr:'١٨ يوما',podEn:'Designer T2+ · Writer · Photographer',podAr:'مصمم T2+ · كاتب · مصور',
 solvesEn:'Phone-photo menus and no delivery-app profile: covers lost every night.',solvesAr:'قوائم بصور الهاتف، ولا حضور على تطبيقات التوصيل: طاولات تفقد كل ليلة.',
 recEn:['Menu design, print and digital QR, AR and EN','30 food photos edited','Table-talkers and interior signage','Delivery-app profile setup','Opening social pack, 10 posts'],
 recAr:['تصميم القائمة: مطبوعة ورقمية بـ QR، بالعربية والإنجليزية','معالجة ٣٠ صورة طعام','لوحات طاولات ولوحات داخلية','تجهيز الحضور على تطبيقات التوصيل','حزمة افتتاح: ١٠ منشورات'],
 whyEn:'Found on Google, ordered on WhatsApp, tables filled.',whyAr:'يوجد على جوجل، ويطلب على واتساب، وتملأ الطاولات.',
 buyers:['SME'],wave:2,alt:'Restaurant Digital Pack (register)'},
{code:'RP-033',en:'Enterprise Restaurant Suite',ar:'حزمة المطاعم المؤسسية',fam:'enterprise',usd:3500,unit:'',
 daysEn:'35 days',daysAr:'٣٥ يوما',podEn:'Designer T3 · Developer · Photographer · Marketer · PM',podAr:'مصمم T3 · مطور · مصور · مسوق · مدير مشروع',
 solvesEn:'Each branch looks like a different restaurant, and the delivery presence is weak.',solvesAr:'كل فرع يبدو مطعما آخر، والحضور على التوصيل ضعيف.',
 recEn:['Full brand system, ready for many branches','Bilingual site with menu and reservations','60 food photos edited','Delivery-app setup across platforms','QR and print menus','Three months of social management','Signage system','Loyalty-card concept'],
 recAr:['نظام هوية كامل، جاهز لتعدد الفروع','موقع ثنائي اللغة بقائمة وحجوزات','معالجة ٦٠ صورة طعام','تجهيز الحضور على منصات التوصيل','قوائم QR ومطبوعة','إدارة تواصل ثلاثة أشهر','نظام لوحات','تصور بطاقة ولاء'],
 whyEn:'One brand in every branch, and a direct channel that fills them.',whyAr:'هوية واحدة في كل فرع، وقناة مباشرة تملؤها.',
 buyers:['SME','COR'],wave:4,alt:''},
{code:'RP-011',en:'Hotel Digital Presence',ar:'الحضور الرقمي للفنادق',fam:'enterprise',usd:1500,unit:'',
 daysEn:'24 days',daysAr:'٢٤ يوما',podEn:'Developer T2+ · UI · Writer · Photographer',podAr:'مطور T2+ · واجهة · كاتب · مصور',
 solvesEn:'The hotel lives on walk-ins, invisible online, with no direct way to enquire.',solvesAr:'الفندق يعيش على الزائر العابر، غائبا على الشبكة، دون قناة استفسار مباشرة.',
 recEn:['Bilingual hotel site with room showcase and enquiry form','40 property photos edited','Google Business Profile','3 booking-platform listings, copy and photos','Review-response playbook'],
 recAr:['موقع فندقي ثنائي اللغة بعرض الغرف ونموذج استفسار','معالجة ٤٠ صورة للمنشأة','تسجيل النشاط على جوجل','٣ ملفات على منصات الحجز: نص وصور','دليل الرد على التقييمات'],
 whyEn:'A direct booking channel that pays no platform commission.',whyAr:'قناة حجز مباشرة لا تدفع عمولة لمنصة.',
 buyers:['SME','COR'],wave:2,alt:''},
{code:'RP-034',en:'Hotel Revenue Suite',ar:'حزمة إيرادات الفنادق',fam:'enterprise',usd:3800,unit:'',
 daysEn:'35 days',daysAr:'٣٥ يوما',podEn:'Developer T3 · UI · Photographer · Marketer · PM',podAr:'مطور T3 · واجهة · مصور · مسوق · مدير مشروع',
 solvesEn:'Rooms sell only through platforms, and only at platform margins.',solvesAr:'الغرف تباع عبر المنصات وحدها، وبهامش المنصات.',
 recEn:['Multilingual site with a booking-request engine','60 property photos edited','Google Business and 4 booking-platform listings managed','Review-management system','Three months of social','Email-enquiry automation','Rate display'],
 recAr:['موقع متعدد اللغات بمحرك طلبات حجز','معالجة ٦٠ صورة للمنشأة','إدارة جوجل و٤ منصات حجز','نظام إدارة التقييمات','إدارة تواصل ثلاثة أشهر','أتمتة استفسارات البريد','عرض الأسعار'],
 whyEn:'Direct bookings, paid demand, and guests answered around the clock.',whyAr:'حجوزات مباشرة، وطلب مدفوع، وضيوف يجابون على مدار الساعة.',
 buyers:['SME','COR'],wave:4,alt:''},
{code:'RP-035',en:'Executive & Personal Brand',ar:'الهوية الشخصية للقيادات',fam:'enterprise',usd:900,unit:'',
 daysEn:'14 days',daysAr:'١٤ يوما',podEn:'Writer T3 · Designer · Marketer',podAr:'كاتب T3 · مصمم · مسوق',
 solvesEn:'A capable leader is invisible to partners, press, and investors.',solvesAr:'قيادة قادرة، غير مرئية للشركاء والصحافة والمستثمرين.',
 recEn:['Personal brand strategy','LinkedIn profile rewritten, with banner','Professional bio, AR and EN, in three lengths','One-page media kit','Headshot direction','10 thought-leadership drafts','A one-page personal site'],
 recAr:['استراتيجية الحضور الشخصي','إعادة كتابة حساب لينكدإن مع الغلاف','نبذة مهنية بالعربية والإنجليزية، بثلاثة أطوال','ملف إعلامي من صفحة','توجيه جلسة التصوير','١٠ مسودات منشورات قيادية','موقع شخصي من صفحة'],
 whyEn:'Be found, and be taken seriously, by partners, press, and investors.',whyAr:'أن يجدك الشريك والصحافة والمستثمر، وأن يأخذك بجدية.',
 buyers:['COR','IND'],wave:3,alt:''},
{code:'RP-032',en:'Startup-in-a-Box',ar:'حزمة تأسيس متكاملة',fam:'packages',usd:500,unit:'tiered',
 daysEn:'10–30 days',daysAr:'١٠–٣٠ يوما',podEn:'Multi-role pod · PM',podAr:'بود متعدد الأدوار · مدير مشروع',
 solvesEn:'A new company needs brand, site, presence and paperwork at once, and has one budget for all of it.',solvesAr:'الشركة الجديدة تحتاج الهوية والموقع والحضور معا، ولها ميزانية واحدة للجميع.',
 recEn:['ESSENTIALS · $500 — logo, business card, 3-page website, two platforms set up, one month of content calendar','PROFESSIONAL · $1,200 — adds brand guidelines, 7-page CMS site, business email, letterhead and invoice templates, pitch deck, 3-month content plan','PREMIUM · $2,500 — adds marketing strategy, competitor analysis, CRM setup, 6 months of social management, monthly reporting'],
 recAr:['الأساسية · ٥٠٠$ — شعار، بطاقة عمل، موقع ٣ صفحات، تجهيز منصتين، تقويم محتوى شهر','المهنية · ١٢٠٠$ — تضيف دليل هوية، موقع ٧ صفحات بإدارة محتوى، بريد رسمي، ورق رسمي وقوالب فواتير، عرضا تقديميا، خطة محتوى ٣ أشهر','المتقدمة · ٢٥٠٠$ — تضيف استراتيجية تسويق، تحليل منافسين، نظام عملاء، إدارة تواصل ٦ أشهر، تقارير شهرية'],
 whyEn:'Everything a new company needs, in one funded order.',whyAr:'كل ما يحتاجه نشاط جديد، في أمر واحد ممول.',
 buyers:['FND'],wave:1,alt:''}
];
