/* Kayan · Ready Products — the 68 scope-priced cards
   Source: KAY-PRD-001 Ready Products Operating Catalogue (register). Prices tokenised (F-19),
   so each of these is priced against a written scope before any money moves. */
window.KAYAN_RP = window.KAYAN_RP || {};
window.KAYAN_RP.range = [
{code:'PR-001',en:'Landing Page in 48 Hours',ar:'صفحة هبوط في ٤٨ ساعة',fam:'digital',
 getEn:'A single, sharp page built to convert — live in two days.',getAr:'صفحة واحدة محكمة، مبنية للتحويل، تنشر في يومين.',
 whyEn:'One page, one goal, live by the day after tomorrow.',whyAr:'صفحة واحدة لهدف واحد، تعمل بعد غد.',
 timeEn:'48 hours',timeAr:'٤٨ ساعة',speed:1,buyers:['FND','SME']},
{code:'PR-002',en:'Business Site in Five Days',ar:'موقع أعمال في خمسة أيام',fam:'digital',
 getEn:'A clean, fast, mobile-first site of up to five pages, live in five days.',getAr:'موقع سريع حتى خمس صفحات، يبدأ من الهاتف، ينشر في خمسة أيام.',
 whyEn:'A serious presence, live this week — not this quarter.',whyAr:'حضور جدي هذا الأسبوع، لا هذا الربع.',
 timeEn:'5 days',timeAr:'٥ أيام',speed:1,buyers:['FND','SME']},
{code:'PR-004',en:'Booking & Reservations Site',ar:'موقع حجوزات ومواعيد',fam:'digital',
 getEn:'A site that takes bookings — for a clinic, a salon, a hotel, a service.',getAr:'موقع يستقبل الحجوزات: عيادة، أو صالون، أو فندق، أو خدمة.',
 whyEn:'Stop taking bookings by phone all day; let the site do it.',whyAr:'لا حجز بالهاتف طول اليوم؛ الموقع يتولاه.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['SME']},
{code:'PR-010',en:'Website Copy that Sells',ar:'نصوص موقع تقنع وتبيع',fam:'content',
 getEn:'Persuasive, Arabic-first copy for a site or a campaign.',getAr:'نصوص عربية أولا، مقنعة، لموقع أو حملة.',
 whyEn:'Words that turn a visitor into a customer, not just fill a page.',whyAr:'كلمات تحول الزائر إلى عميل، لا تملأ الصفحة فقط.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['FND','SME']},
{code:'PR-011',en:'Company Profile',ar:'الملف التعريفي للشركة',fam:'content',
 getEn:'A polished company profile that makes a small firm look established.',getAr:'ملف تعريفي مصقول يظهر المنشأة الصغيرة راسخة.',
 whyEn:'The document that wins the meeting before you walk in.',whyAr:'الوثيقة التي تكسب الاجتماع قبل حضوره.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['FND','SME']},
{code:'PR-012',en:'Article & Blog Pack',ar:'حزمة مقالات ومدونة',fam:'content',
 getEn:'A set of well-written, search-friendly articles in Arabic or English.',getAr:'مقالات محكمة الصياغة، مهيأة للبحث، بالعربية أو الإنجليزية.',
 whyEn:'Content that brings people in, month after month.',whyAr:'محتوى يجلب الناس شهرا بعد شهر.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['SME','COR']},
{code:'PR-013',en:'Product Descriptions at Scale',ar:'أوصاف منتجات بالحجم الكبير',fam:'content',
 getEn:'Clear, selling descriptions for a whole catalogue of products.',getAr:'أوصاف واضحة بائعة لكتالوج كامل.',
 whyEn:'Every product described to sell — not left blank or copied.',whyAr:'كل منتج يوصف ليباع، لا يترك فارغا ولا ينسخ.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['SME']},
{code:'PR-014',en:'Ghostwriting',ar:'كتابة بالإنابة',fam:'content',
 getEn:'Articles, speeches, or thought-leadership written in your voice.',getAr:'مقالات وكلمات ومواقف قيادية تكتب بصوتك.',
 whyEn:'Your ideas, written the way you would if you had the time.',whyAr:'أفكارك مكتوبة كما تكتبها لو اتسع الوقت.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','IND']},
{code:'PR-015',en:'Newsletter Setup & Writing',ar:'رسالة بريدية: تجهيز وكتابة',fam:'content',
 getEn:'A newsletter set up and written to keep your audience close.',getAr:'رسالة بريدية تجهز وتكتب لتقرب الجمهور.',
 whyEn:'Stay in your customers’ inbox, not just in their memory.',whyAr:'أن تبقى في بريد العميل، لا في ذاكرته فقط.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['SME','NGO']},
{code:'PR-016',en:'Certified Translation',ar:'ترجمة معتمدة',fam:'translation',
 getEn:'Accurate, certified Arabic⇄English translation of a document.',getAr:'ترجمة معتمدة دقيقة، عربي⇄إنجليزي، لوثيقة.',
 whyEn:'Accepted where it counts — embassies, universities, courts.',whyAr:'تقبل حيث يهم: السفارات والجامعات والمحاكم.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['IND','DIA']},
{code:'PR-017',en:'Academic Document Package',ar:'حزمة الوثائق الأكاديمية',fam:'translation',
 getEn:'Transcripts, certificates, and letters translated and prepared for study abroad.',getAr:'كشوف الدرجات والشهادات والخطابات، تترجم وتجهز للدراسة في الخارج.',
 whyEn:'Your whole academic file, ready for the application.',whyAr:'ملفك الأكاديمي كاملا، جاهزا للتقديم.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['IND','DIA']},
{code:'PR-018',en:'Contract & Legal Translation',ar:'ترجمة عقود ووثائق قانونية',fam:'translation',
 getEn:'Precise translation of contracts and legal documents.',getAr:'ترجمة دقيقة للعقود والوثائق القانونية.',
 whyEn:'Every clause right, because a wrong word can cost you.',whyAr:'كل بند في موضعه؛ فكلمة خاطئة تكلف.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['COR','DIA']},
{code:'PR-019',en:'Document Handling & Attestation',ar:'إنجاز الوثائق والتصديقات',fam:'translation',
 getEn:'Someone on the ground to process, attest, and prepare your papers.',getAr:'من يقف على الأرض، فينجز الأوراق ويصدقها ويجهزها.',
 whyEn:'The queues and the counters, handled by someone who knows them.',whyAr:'الطوابير والنوافذ يتولاها من يعرفها.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA','IND']},
{code:'PR-020',en:'Subtitling & Captioning',ar:'سترجة وتعليق نصي',fam:'translation',
 getEn:'Arabic video subtitled or captioned, accurately and on time.',getAr:'فيديو عربي يسترج بدقة وفي الموعد.',
 whyEn:'Your video understood by everyone who watches it.',whyAr:'فيديو يفهمه كل من يشاهده.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['COR','NGO']},
{code:'PR-021',en:'Transcription',ar:'تفريغ صوتي',fam:'translation',
 getEn:'Arabic audio or video turned into accurate text.',getAr:'صوت أو فيديو عربي يتحول إلى نص دقيق.',
 whyEn:'Hours of recording, turned into a document you can use.',whyAr:'ساعات تسجيل تتحول إلى وثيقة تستخدم.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['NGO','COR']},
{code:'PR-022',en:'Interpretation',ar:'ترجمة فورية',fam:'translation',
 getEn:'A professional interpreter for a meeting, remote or in person.',getAr:'مترجم فوري مهني لاجتماع، حضوريا أو عن بعد.',
 whyEn:'Understood in the room, in real time.',whyAr:'أن تفهم في القاعة، لحظة بلحظة.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['COR','NGO']},
{code:'PR-023',en:'Arabic Data Annotation at Scale',ar:'توسيم بيانات عربية بالحجم الكبير',fam:'data',
 getEn:'Text or image annotation to your standard, measured against a gold set.',getAr:'توسيم نصوص أو صور بمعيارك، يقاس على مجموعة مرجعية.',
 whyEn:'The data the AI economy runs on — careful, and cost-competitive.',whyAr:'البيانات التي يقوم عليها اقتصاد الذكاء الاصطناعي: دقيقة، وتنافسية الكلفة.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','DIA']},
{code:'PR-024',en:'Paper to Digital',ar:'من الورق إلى الرقمي',fam:'data',
 getEn:'Decades of paper records scanned, organised, and made searchable.',getAr:'سجلات ورقية لعقود، تمسح وتنظم وتصبح قابلة للبحث.',
 whyEn:'An archive safe from fire, flood, and time — and findable in seconds.',whyAr:'أرشيف يأمن من الحريق والماء والزمن، ويوجد في ثوان.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','GOV','NGO']},
{code:'PR-025',en:'Data Entry at Scale',ar:'إدخال بيانات بالحجم الكبير',fam:'data',
 getEn:'Large volumes of data entered accurately and checked.',getAr:'كميات كبيرة تدخل بدقة وتراجع.',
 whyEn:'The tedious work done right, so you do not have to.',whyAr:'العمل الممل ينجز صحيحا، فلا تتولاه.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['COR','NGO']},
{code:'PR-026',en:'Dataset Creation',ar:'بناء مجموعة بيانات',fam:'data',
 getEn:'A clean, structured Arabic dataset built to your specification.',getAr:'مجموعة بيانات عربية منظفة ومهيكلة على مواصفتك.',
 whyEn:'A dataset that is actually usable, not just large.',whyAr:'مجموعة قابلة للاستخدام فعلا، لا كبيرة فقط.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR']},
{code:'PR-027',en:'Survey Data Processing',ar:'معالجة بيانات المسوح',fam:'data',
 getEn:'Raw survey data cleaned, coded, and made ready to analyse.',getAr:'بيانات مسح خام، تنظف وترمز وتجهز للتحليل.',
 whyEn:'From messy field returns to numbers you can trust.',whyAr:'من عائد ميداني مشوش إلى أرقام تعتمد.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['NGO','GOV']},
{code:'PR-028',en:'Brand in 48 Hours',ar:'هوية في ٤٨ ساعة',fam:'brand',
 getEn:'A logo, colours, and the basics of an identity — in two days.',getAr:'شعار وألوان وأساسيات هوية، في يومين.',
 whyEn:'Look like an institution by tomorrow morning.',whyAr:'أن تظهر مؤسسة صباح الغد.',
 timeEn:'48 hours',timeAr:'٤٨ ساعة',speed:1,buyers:['FND']},
{code:'PR-030',en:'Logo Design',ar:'تصميم شعار',fam:'brand',
 getEn:'A distinctive, professional logo, delivered ready to use.',getAr:'شعار مميز مهني، يسلم جاهزا للاستخدام.',
 whyEn:'A mark people remember, not a clip-art guess.',whyAr:'علامة تذكر، لا اقتباسا جاهزا.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['FND','IND']},
{code:'PR-031',en:'Packaging Design',ar:'تصميم تغليف',fam:'brand',
 getEn:'Product packaging designed to stand out on a shelf.',getAr:'تغليف مصمم ليتميز على الرف.',
 whyEn:'The reason a hand reaches for yours and not the next one.',whyAr:'السبب الذي يجعل اليد تمتد إلى منتجك لا إلى جاره.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['SME','COR']},
{code:'PR-032',en:'Menu Design',ar:'تصميم قائمة طعام',fam:'brand',
 getEn:'A menu designed to look good and sell the right dishes.',getAr:'قائمة مصممة لتبدو حسنة، ولتبيع الأطباق الصحيحة.',
 whyEn:'A menu that makes people order more, and better.',whyAr:'قائمة تجعل الطلب أكثر وأفضل.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['SME']},
{code:'PR-033',en:'Signage & Storefront',ar:'لوحات وواجهة متجر',fam:'brand',
 getEn:'Signage and storefront design that pulls people in.',getAr:'تصميم لوحات وواجهة يجذب الداخلين.',
 whyEn:'The first thing a customer sees, done right.',whyAr:'أول ما يراه العميل، متقنا.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['SME']},
{code:'PR-034',en:'Print Pack',ar:'حزمة مطبوعات',fam:'brand',
 getEn:'Business cards, flyers, and brochures — one coordinated set.',getAr:'بطاقات ومنشورات وكتيبات: طقم واحد متناسق.',
 whyEn:'Everything you hand someone, looking like it belongs together.',whyAr:'كل ما تسلمه بيدك، يبدو من عائلة واحدة.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['FND','SME']},
{code:'PR-036',en:'Explainer Video',ar:'فيديو توضيحي',fam:'media',
 getEn:'A short animated video that makes your offer clear in a minute.',getAr:'فيديو قصير متحرك يوضح عرضك في دقيقة.',
 whyEn:'What you do, understood in sixty seconds.',whyAr:'ما تفعله، يفهم في ستين ثانية.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['FND','COR']},
{code:'PR-037',en:'Product Photography',ar:'تصوير منتجات',fam:'media',
 getEn:'Professional photographs of your products, ready to sell.',getAr:'صور مهنية لمنتجاتك، جاهزة للبيع.',
 whyEn:'Photos that make people want it — not phone snaps.',whyAr:'صور ترغب، لا لقطات هاتف.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['SME']},
{code:'PR-038',en:'Event Photography & Video',ar:'تصوير فعاليات: صورة وفيديو',fam:'media',
 getEn:'A photographer and a videographer for your event or occasion.',getAr:'مصور ومصور فيديو لفعاليتك أو مناسبتك.',
 whyEn:'The day, captured properly, to keep and to share.',whyAr:'اليوم يحفظ كما يستحق، ليبقى ويشارك.',
 timeEn:'Short',timeAr:'قصير',speed:2,buyers:['SME','COR','DIA']},
{code:'PR-040',en:'Podcast Production',ar:'إنتاج بودكاست',fam:'media',
 getEn:'A podcast set up and produced — recording, editing, and polish.',getAr:'بودكاست يجهز وينتج: تسجيل ومونتاج وصقل.',
 whyEn:'Your voice, produced to a standard people will listen to.',whyAr:'صوتك منتجا بمستوى يستمع إليه.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','NGO']},
{code:'PR-041',en:'Brand Video',ar:'فيلم مؤسسي',fam:'media',
 getEn:'A polished film that tells your organisation’s story.',getAr:'فيلم مصقول يحكي قصة مؤسستك.',
 whyEn:'The film that makes people feel what you do, not just hear it.',whyAr:'فيلم يشعر الناس بما تفعله، لا يخبرهم به فقط.',
 timeEn:'Medium–Long',timeAr:'متوسط–طويل',speed:4,buyers:['COR','NGO']},
{code:'PR-043',en:'Social Media Starter',ar:'انطلاقة وسائل التواصل',fam:'marketing',
 getEn:'Accounts set up properly and the first month of content, done.',getAr:'حسابات تجهز على الوجه الصحيح، وشهر أول من المحتوى منجزا.',
 whyEn:'Start right, so the first impression is a strong one.',whyAr:'بداية صحيحة، فيكون الأثر الأول قويا.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['FND','SME']},
{code:'PR-046',en:'WhatsApp Business Setup',ar:'تجهيز واتساب للأعمال',fam:'marketing',
 getEn:'A WhatsApp Business account set up with a catalogue and quick replies.',getAr:'حساب واتساب للأعمال يجهز بكتالوج وردود سريعة.',
 whyEn:'Sell where your customers already are, set up properly.',whyAr:'أن تبيع حيث عميلك أصلا، بتجهيز صحيح.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['SME']},
{code:'PR-047',en:'Google Business Setup',ar:'تسجيل النشاط على خرائط جوجل',fam:'marketing',
 getEn:'Your business on Google Maps and Search, set up and optimised.',getAr:'نشاطك على خرائط جوجل والبحث، مسجلا ومحسنا.',
 whyEn:'Found the moment someone nearby searches for what you sell.',whyAr:'أن توجد لحظة يبحث القريب عما تبيع.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['SME']},
{code:'PR-048',en:'Content Calendar & Strategy',ar:'تقويم محتوى واستراتيجية',fam:'marketing',
 getEn:'A month of planned content and a clear strategy behind it.',getAr:'شهر من المحتوى المخطط، وخلفه استراتيجية واضحة.',
 whyEn:'A plan, so posting is deliberate and not last-minute.',whyAr:'خطة، فيكون النشر مقصودا لا مرتجلا.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['SME','COR']},
{code:'PR-049',en:'Business Plan',ar:'خطة عمل متكاملة',fam:'business',
 getEn:'A funder-ready or investor-ready business plan.',getAr:'خطة عمل جاهزة للممول أو المستثمر.',
 whyEn:'The plan that gets the loan, the investor, or the licence.',whyAr:'الخطة التي تحصل التمويل أو المستثمر أو الترخيص.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['FND','COR']},
{code:'PR-050',en:'Feasibility Study',ar:'دراسة جدوى',fam:'business',
 getEn:'An honest study of whether an idea will work, and how.',getAr:'دراسة صادقة: هل تنجح الفكرة، وكيف.',
 whyEn:'Know before you spend, not after.',whyAr:'أن تعرف قبل أن تصرف، لا بعده.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['FND','COR','GOV']},
{code:'PR-054',en:'Mystery Shopping & Field Research',ar:'تقصي ميداني وعميل خفي',fam:'business',
 getEn:'Trained researchers gathering real evidence on the ground.',getAr:'باحثون مدربون يجمعون دليلا حقيقيا من الأرض.',
 whyEn:'See your business, or your market, as it really is.',whyAr:'أن ترى نشاطك أو سوقك كما هو فعلا.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','GOV']},
{code:'PR-055',en:'Competitor Analysis',ar:'تحليل المنافسين',fam:'business',
 getEn:'A clear picture of who you are up against, and where the gap is.',getAr:'صورة واضحة لمن تنافسه، وأين الفرجة.',
 whyEn:'Know exactly where you can win.',whyAr:'أن تعرف بالضبط أين تكسب.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['FND','COR']},
{code:'PR-056',en:'The Proposal that Wins',ar:'مقترح المانحين',fam:'development',
 getEn:'A funder-ready proposal, structured and written to win the grant.',getAr:'مقترح جاهز للمانح، مهيكل ومكتوب لكسب المنحة.',
 whyEn:'Structured the way funders score, written to win.',whyAr:'يهيكل كما يقيم المانح، ويكتب ليكسب.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['NGO']},
{code:'PR-057',en:'Report Writing',ar:'كتابة تقارير المانحين',fam:'development',
 getEn:'Donor and technical reports written to standard and on time.',getAr:'تقارير المانحين والتقارير الفنية، تكتب بالمعيار وفي الموعد.',
 whyEn:'Reports that satisfy the donor and get filed without a rewrite.',whyAr:'تقارير ترضي المانح وتقبل دون إعادة كتابة.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['NGO','GOV']},
{code:'PR-058',en:'M&E Framework',ar:'إطار المتابعة والتقييم',fam:'development',
 getEn:'A monitoring and evaluation framework that stands up to scrutiny.',getAr:'إطار متابعة وتقييم يصمد أمام التدقيق.',
 whyEn:'Show your impact in a way an evaluator will accept.',whyAr:'أن تبرهن أثرك بصيغة يقبلها المقيم.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['NGO']},
{code:'PR-059',en:'Needs Assessment',ar:'تقييم احتياجات',fam:'development',
 getEn:'A rigorous assessment of needs, with evidence and recommendations.',getAr:'تقييم منهجي للاحتياجات، بالدليل والتوصيات.',
 whyEn:'The evidence base a serious intervention starts from.',whyAr:'قاعدة الدليل التي يبدأ منها تدخل جدي.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['NGO','GOV']},
{code:'PR-061',en:'Third-Party Monitoring',ar:'رقابة طرف ثالث',fam:'development',
 getEn:'Independent monitoring of a project or a programme.',getAr:'رقابة مستقلة على مشروع أو برنامج.',
 whyEn:'Independent eyes, so the donor trusts the result.',whyAr:'عين مستقلة، فيثق المانح بالنتيجة.',
 timeEn:'Medium / ongoing',timeAr:'متوسط · متجدد',speed:4,buyers:['NGO','GOV']},
{code:'PR-063',en:'Case Studies & Stories',ar:'قصص الأثر ودراسات الحالة',fam:'development',
 getEn:'Human stories and case studies that show a programme’s impact.',getAr:'قصص إنسانية ودراسات حالة تظهر أثر البرنامج.',
 whyEn:'The stories that make a report land with a donor.',whyAr:'القصص التي تجعل التقرير يستقر عند المانح.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['NGO']},
{code:'PR-064',en:'Event Managed End to End',ar:'فعالية تدار من الطرف إلى الطرف',fam:'events',
 getEn:'An event planned and run, from logistics to the day itself.',getAr:'فعالية تخطط وتدار، من اللوجستيات إلى اليوم نفسه.',
 whyEn:'Be a guest at your own event, not its stressed organiser.',whyAr:'أن تحضر فعاليتك ضيفا، لا منظما مكدودا.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','NGO']},
{code:'PR-065',en:'Workshop, Run for You',ar:'ورشة تدار عنك',fam:'events',
 getEn:'A workshop designed and facilitated — content, room, and materials.',getAr:'ورشة تصمم وتيسر: المحتوى والقاعة والمواد.',
 whyEn:'A workshop that runs itself, because someone else ran it.',whyAr:'ورشة تسير من نفسها، لأن غيرك أدارها.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['COR','NGO']},
{code:'PR-066',en:'Conference & Exhibition',ar:'مؤتمر ومعرض',fam:'events',
 getEn:'A larger conference or exhibition managed end to end.',getAr:'مؤتمر أو معرض أكبر، يدار كاملا.',
 whyEn:'A big day that runs like it was easy.',whyAr:'يوم كبير يسير كأنه هين.',
 timeEn:'Medium–Long',timeAr:'متوسط–طويل',speed:4,buyers:['COR','GOV']},
{code:'PR-067',en:'Wedding & Occasion',ar:'زفاف ومناسبة',fam:'events',
 getEn:'A wedding or family occasion coordinated, start to finish.',getAr:'زفاف أو مناسبة أسرية، تنسق من أولها إلى آخرها.',
 whyEn:'The day right, so the family can simply be in it.',whyAr:'يوم متقن، فتكون الأسرة فيه لا عليه.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['IND','DIA']},
{code:'PR-068',en:'Hub Event Hosting',ar:'استضافة الفعاليات في المركز',fam:'events',
 getEn:'Your event hosted at the Hub, with the space and the support included.',getAr:'فعاليتك تستضاف في المركز، بالمكان والمساندة معا.',
 whyEn:'A ready, respected venue and a team who runs it.',whyAr:'مكان جاهز محترم، وفريق يديره.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['SME','FND']},
{code:'PR-069',en:'Career Launch Pack',ar:'حزمة انطلاق المسار المهني',fam:'career',
 getEn:'A CV, a LinkedIn profile, and a cover letter — the full set.',getAr:'سيرة ذاتية، وحساب لينكدإن، وخطاب تقديم: الطقم كاملا.',
 whyEn:'Everything an employer looks at, done to win.',whyAr:'كل ما ينظر إليه المشغل، معدا للكسب.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['IND']},
{code:'PR-070',en:'The Winning CV',ar:'السيرة الذاتية الرابحة',fam:'career',
 getEn:'A CV built to pass the scan and the filter, and get the interview.',getAr:'سيرة مبنية لتجاوز النظرة السريعة والفلترة الآلية، وتحصل المقابلة.',
 whyEn:'Built to pass the six-second scan and the software filter.',whyAr:'مبنية لتجاوز نظرة ست ثوان، وفلترة برنامج.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['IND']},
{code:'PR-071',en:'LinkedIn Makeover',ar:'إعادة بناء حساب لينكدإن',fam:'career',
 getEn:'A LinkedIn profile rebuilt to be found and to impress.',getAr:'حساب لينكدإن يعاد بناؤه ليوجد وليؤثر.',
 whyEn:'Found by recruiters, and trusted when they land.',whyAr:'أن يجدك المشغل، وأن يثق بما يجد.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['IND']},
{code:'PR-072',en:'Scholarship Application Package',ar:'حزمة التقديم على المنح',fam:'career',
 getEn:'A full application — essays, documents, and polish — for a scholarship.',getAr:'ملف تقديم كامل: المقالات والوثائق والصقل، لمنحة دراسية.',
 whyEn:'The application that turns a long shot into an offer.',whyAr:'ملف يحول الاحتمال البعيد إلى قبول.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['IND','DIA']},
{code:'PR-073',en:'University Application Support',ar:'مساندة التقديم الجامعي',fam:'career',
 getEn:'Guidance and preparation for applying to study, at home or abroad.',getAr:'إرشاد وتجهيز للتقديم على الدراسة، في الداخل أو الخارج.',
 whyEn:'The whole application, done right the first time.',whyAr:'الملف كاملا، متقنا من المرة الأولى.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['IND','DIA']},
{code:'PR-074',en:'Interview Coaching',ar:'تدريب على المقابلات',fam:'career',
 getEn:'Practice and preparation that makes an interview winnable.',getAr:'تمرين وتجهيز يجعلان المقابلة قابلة للكسب.',
 whyEn:'Walk in ready, not hoping.',whyAr:'أن تدخل مستعدا، لا راجيا.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['IND']},
{code:'PR-075',en:'Portfolio Building',ar:'بناء ملف الأعمال',fam:'career',
 getEn:'A professional portfolio for a creative, a developer, or a specialist.',getAr:'ملف أعمال مهني لمبدع أو مطور أو أخصائي.',
 whyEn:'Proof of what you can do, arranged to get you hired.',whyAr:'دليل على ما تقدر عليه، مرتبا ليوظفك.',
 timeEn:'Short–Medium',timeAr:'قصير–متوسط',speed:2,buyers:['IND']},
{code:'PR-076',en:'The Trusted Hand',ar:'اليد الموثوقة',fam:'homeland',
 getEn:'Someone credible on the ground to run errands, handle papers, and report back.',getAr:'من يعتمد عليه على الأرض: ينجز المهام ويتولى الأوراق ويبلغ بما جرى.',
 whyEn:'Someone you can trust at home, who sends proof it was done.',whyAr:'من تثق به في الوطن، ويرسل إليك ما يثبت الإنجاز.',
 timeEn:'Ongoing / per task',timeAr:'متجدد · بالمهمة',speed:2,buyers:['DIA']},
{code:'PR-077',en:'Build-Home Bundle',ar:'حزمة البناء في الوطن',fam:'homeland',
 getEn:'A site, a brand, and a presence for a venture you are building at home from abroad.',getAr:'موقع وهوية وحضور، لنشاط تبنيه في الوطن وأنت خارجه.',
 whyEn:'Start your business at home without booking a flight.',whyAr:'أن تبدأ نشاطك في الوطن دون حجز رحلة.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA']},
{code:'PR-078',en:'Remote Team as a Service',ar:'فريق في الوطن يدار عنك',fam:'homeland',
 getEn:'A verified team at home delivering ongoing work for you abroad, managed by Kayan.',getAr:'فريق موثق في الوطن ينجز لك عملا متجددا وأنت في الخارج، تديره كيان.',
 whyEn:'Your own team in Yemen, run for you, results sent to you.',whyAr:'فريقك في اليمن، يدار عنك، وتصلك نتائجه.',
 timeEn:'Ongoing',timeAr:'متجدد',speed:4,buyers:['DIA']},
{code:'PR-079',en:'Family Occasion, Handled',ar:'مناسبة الأسرة، تدار كاملة',fam:'homeland',
 getEn:'A wedding or occasion for your family back home, coordinated from abroad.',getAr:'زفاف أو مناسبة لأسرتك في الوطن، تنسق من الخارج.',
 whyEn:'Give your family the day, even when you cannot be at it.',whyAr:'أن تهدي أسرتك اليوم، وإن لم تحضره.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA']},
{code:'PR-080',en:'Property Check & Documentation',ar:'فحص العقار وتوثيقه',fam:'homeland',
 getEn:'Your property visited, verified, photographed, and documented, with a full report.',getAr:'عقارك يزار ويتحقق منه ويصور ويوثق، مع تقرير كامل.',
 whyEn:'Know the truth about your property at home, with proof.',whyAr:'أن تعرف حقيقة عقارك في الوطن، بالدليل.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA']},
{code:'PR-081',en:'Procurement & Delivery',ar:'شراء وتوصيل',fam:'homeland',
 getEn:'We buy what your family needs and deliver it, with confirmation.',getAr:'يشترى ما تحتاجه الأسرة ويوصل، بإقرار استلام.',
 whyEn:'Send what is needed, not just money — and see it arrive.',whyAr:'أن ترسل الحاجة لا المال فقط، وأن ترى وصولها.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['DIA']},
{code:'PR-082',en:'Gift Package to Family',ar:'هدية إلى الأسرة',fam:'homeland',
 getEn:'A gift chosen, prepared, and delivered to your family for an occasion.',getAr:'هدية تختار وتجهز وتوصل إلى أسرتك في مناسبة.',
 whyEn:'Be present at home on the day, through something in their hands.',whyAr:'أن تحضر يومهم، بشيء في أيديهم.',
 timeEn:'Short',timeAr:'قصير',speed:1,buyers:['DIA']},
{code:'PR-083',en:'The Family Archive',ar:'أرشيف الأسرة',fam:'homeland',
 getEn:'Your family’s photographs, documents, and elders’ stories preserved before they are lost.',getAr:'صور الأسرة ووثائقها وروايات كبارها، تحفظ قبل أن تفقد.',
 whyEn:'Save the stories and the faces while they are still here to save.',whyAr:'أن تحفظ الرواية والوجوه ما دامت باقية.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA']},
{code:'PR-084',en:'Business Setup at Home',ar:'تأسيس نشاط في الوطن',fam:'homeland',
 getEn:'A business established at home — brand, presence, and a team to run it.',getAr:'نشاط يؤسس في الوطن: هوية وحضور وفريق يشغله.',
 whyEn:'A real operation at home, built and staffed, reporting to you.',whyAr:'عمل حقيقي في الوطن، مبني وموظف، يرفع إليك تقاريره.',
 timeEn:'Medium–Long',timeAr:'متوسط–طويل',speed:4,buyers:['DIA']},
{code:'PR-085',en:'Due Diligence & Market Entry',ar:'فحص نافي للجهالة ودخول السوق',fam:'homeland',
 getEn:'Honest research and checks for a diaspora investor looking at home.',getAr:'بحث وتحقق صادقان لمستثمر مغترب ينظر إلى الوطن.',
 whyEn:'Invest at home with your eyes open, not on hope.',whyAr:'أن تستثمر في الوطن بعين مفتوحة، لا على أمل.',
 timeEn:'Medium',timeAr:'متوسط',speed:3,buyers:['DIA']}
];
