export const routes = [
  ['/', 'Kayan Home.dc.html'],
  ['/record', 'Kayan Record.dc.html'],
  ['/seal', 'Kayan Seal.dc.html'],
  ['/charter', 'Kayan Charter.dc.html'],
  ['/journey', 'Kayan Journey.dc.html'],
  ['/clients', 'Kayan for Clients.dc.html'],
  ['/clients/account', 'Kayan Client Profile.dc.html'],
  ['/talent', 'Kayan for Talent.dc.html'],
  ['/talent/profile', 'Kayan Talent Profile.dc.html'],
  ['/tools/scope', 'Kayan Toolkit - Scoping Form.dc.html'],
  ['/lines/delivery', 'Line I - Managed Delivery.dc.html'],
  ['/en/lines/delivery', 'Line I - Managed Delivery EN.dc.html'],
  ['/lines/products', 'Line I - Ready Products.dc.html'],
  ['/lines/hub', 'Line II - The Hub and Cafe.dc.html'],
  ['/en/lines/hub', 'Line II - The Hub and Cafe EN.dc.html'],
  ['/hub-location', 'Kayan Hub.html'],
  ['/lines/forge', 'Line III - The Forge.dc.html'],
  ['/en/lines/forge', 'Line III - The Forge EN.dc.html'],
  ['/k4y', 'Civic Wing - Kayan for Yemen.dc.html'],
  ['/people', 'Kayan People.dc.html'],
  ['/planet', 'Kayan Planet.dc.html'],
  ['/legal', 'Kayan Legal.dc.html'],
  ['/atlas', 'Kayan Atlas.html'],
  ['/voyage', 'Kayan Dimension.html'],
  ['/access', 'Kayan Access.dc.html'],
  ['/apply', 'Kayan Apply.dc.html'],
  ['/portal', 'Kayan Portal.dc.html'],
  ['/space/client', 'Kayan Space - Client.dc.html'],
  ['/space/talent', 'Kayan Space - Talent.dc.html'],
  ['/pod/:code?', 'Kayan Pod Room.dc.html'],
  ['/admin', 'Kayan Admin.dc.html'],
];

export const fileToRoute = new Map(
  routes.map(([route, file]) => [file.toLocaleLowerCase(), route.replace('/:code?', '')]),
);
